config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sendemail.users.urls')),
]

sendemail/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
	path('', views.UserCreateView.as_view(), name="home"),
	path('suscripcion-exitosa', views.UserSuccessSuscriptionView.as_view(), name="success_suscription"),
]

sendemail/users/models.py
from django.db import models

# Create your models here.

sendemail/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .tasks import enviar_correo


class UserForm(UserCreationForm):
	
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['email'].required = True
		self.initial = {
			"username": "",
			"email": ""
		}

	class Meta:
		model = User
		fields = (
			'username',
			'email',
			'password1',
			'password2',
		)

	def send_email(self):
		user = self.save()
		enviar_correo.delay(user.pk)

sendemail/users/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import UserForm


class UserCreateView(generic.CreateView):
	form_class = UserForm
	template_name = 'users/home.html'
	success_url = reverse_lazy('users:success_suscription')

	def form_valid(self, form):
		form.send_email()
		return super().form_valid(form)


class UserSuccessSuscriptionView(generic.TemplateView):
	template_name = "users/success-suscription.html"

sendemail/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} SuscripcionesWeb {% endblock %}</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/font/icon.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/sendemail.css' %}">
</head>
<body>
	<main>
		<header>
			<div class="row">
				<div class="col s12 center">
					<h1 class="display-2"> Suscripciones web </h1>
					<p>Solo suscribete para recibir buenos contenidos. <i class="material-icons">mail</i></p>
				</div>
			</div>
		</header>

		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'materialize/js/materialize.min.js' %}"></script>

		{% block js %} {% endblock %}
	</main>
</body>
</html>

sendemail/templates/users/email-success-suscription.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Suscripción exitosa!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <main>
    <h2>Enhorabuena <strong>{{ user.email }}</strong>!</h2>
    <p>Tu suscripción se hecho exitosamente!
    Ahora podrás recibir notificaciones cada vez que publiquemos nuevos contenidos.
    </p>
  </main>
</body>
</html>

sendemail/templates/users/errors-field.html
{% if field.errors %}
	<span class="helper-text red-text">{{ field.errors }}</span>
{% endif %}

sendemail/templates/users/home.html
{% extends 'base/base.html' %}

{% block title %} {{ block.super }} | Home {% endblock %}

{% block content %}
<div class="row">
	<div class="col s12">
		<article class="card">
			<div class="card-content">
				<h3 class="card-title"> Suscribete! <i class="material-icons left medium">person_add</i></h3>
			</div>
			<div class="card-content">
				<form method="POST" action=""> {% csrf_token %}
					<div class="input-field">
						<input type="text" name="username" id="username" value="{{ form.username.value }}">
						<label for="username">Usuario</label>
						{% include 'users/errors-field.html' with field=form.username %}
					</div>
					<div class="input-field">
						<input type="email" name="email" id="email" value="{{ form.email.value }}">
						<label for="email">Correo</label>
						{% include 'users/errors-field.html' with field=form.email %}
					</div>
					<div class="input-field">
						<input type="password" name="password1" id="password">
						<label for="password">Contraseña</label>
						{% include 'users/errors-field.html' with field=form.password1 %}
					</div>
					<div class="input-field">
						<input type="password" name="password2" id="password2">
						<label for="password2">Confirmar (Contraseña)</label>
						{% include 'users/errors-field.html' with field=form.password2 %}
					</div>
					<button type="submit" class="btn primary">Listo! <i class="material-icons right">send</i></button>
				</form>
			</div>
		</article>
	</div>
</div>
{% endblock %}

sendemail/templates/users/success-suscription.html
{% extends 'base/base.html' %}

{% block title %} {{ block.super }} | Listo! {% endblock %}

{% block content %}
<div class="row">
	<div class="col s12">
		<article class="card">
			<div class="card-content">
				<h4 class="card-title green-text"> Enhorabuena!</h4>
				<p>Te haz suscrito exitosamente en nuestra sitio web. Ahora solo tienes que esperar que te lleguen los contenidos!</p>
			</div>
			<div class="card-action">
				<a href="{% url 'users:home' %}" class="btn primary">Atrás <i class="material-icons right">arrow_back</i></a>
			</div>
		</article>
	</div>
</div>
{% endblock %}